### ISSUE TITLE
`num_cat()` formatting of output and inclusion of lowest values

### ISSUE THREAD

**Issue by gnoblet** [impact-initiatives-hppu/humind#417]
Comments from Yann:

* Do you need to do every 5 years? It ends up with a very long list possibility (and results)?
* Do you need to keep the format (60,65] ? it is a mix between (),[] and numbers. Regex + some function make it very hard to manipulate.

**Comment by lanawwas** [comment]
Putting my thoughts on this, and I will review it again with the help of AI later for better optimization if needed , @gnoblet feel free to comment if anything seems not as intended! 

The enhancement can be as the following:

-   If labels are not provided, generate them automatically based on the following:
    - The lower bound is inclusive (hence lower + 1).
    -  The upper bound is exclusive (as we set right = FALSE in the cut function for better alignment with age).
    - If it's the last category and plus_last = TRUE, we add a "+" instead of the upper bound.
- Add a `plus_last` parameter to allow for a "+" in the last category as optional.
-  Changed `right = TRUE` to `right = FALSE` in the cut function to make the intervals left-closed, right-open, which is more intuitive for age categories based on this logic of implementation such as. The generated labels will now look like `61-65` instead of the current `(60 - 65]`, etc., and the last one could be `96+` instead of `(95, 100]` if `plus_last = TRUE`.

```r
#' Add categories for a numeric variable with improved age category formatting
#[Previous parameters remain the same] 
#' @param plus_last Logical, whether to add a "+" to the last category.
#[Previous parameters remain the same] 

num_cat <- function(df, num_col, breaks, labels = NULL, int_undefined = c(-999, 999), 
                    char_undefined = "Unknown", new_colname = NULL, plus_last = FALSE) {
  
  # [Previous checks remain the same]

  # [Previous new_colname still the same] 
  
  # If labels are not provided, generate them
  if (is.null(labels)) {
    labels <- sapply(1:(length(breaks) - 1), function(i) {
      lower <- breaks[i]
      upper <- breaks[i + 1]
      if (i == length(breaks) - 1 && plus_last) {
        return(paste0(lower + 1, "+"))
      } else {
        return(paste0(lower + 1, "-", upper))
      }
    })
  }
   
  # Create age categories
  df <- dplyr::mutate(df, "{new_colname}" := dplyr::case_when(
    # Replace value in int_dontkow by char_dontknow
    !!rlang::sym(num_col) %in%  int_dontkow ~ char_dontknow,
    # Replace values below 0 by NA
    !!rlang::sym(num_col) < 0 ~ NA_character_,
    # Create categories using function cut and breaks
    .default = cut(!!rlang::sym(num_col), 
                   breaks = breaks, 
                   labels = labels, 
                   include.lowest = TRUE, 
                   right = FALSE)
  ))
  
  return(df)
}
```

Usage example:

```r
df <- data.frame(age = c(3, 7, 12, 25, 40, 55, 70))
result <- num_cat(df, "age", breaks = c(0, 5, 10, 18, 60, Inf), plus_last = TRUE)
print(result)
```
This should give you age categories like "1-5", "6-10", "11-18", "19-60", "61+"

**Comment by gnoblet** [comment]
Out of my mind, should we even allow for labels as an input now? Not sure it's a needed feature.

**Comment by lanawwas** [comment]
> Out of my mind, should we even allow for labels as an input now? Not sure it's a needed feature.

Keeping it won't make a harm in any case I guess!
