### ISSUE TITLE
add_income_source_cat.R - count of how many vars in that income category are non-zero

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#430]
Based on Giovanni's feedback 

> 3-	If I run this code the columns cm_income_source_emergency_n and all other category vars are mostly empty. I thought this was a count of how many vars in that income category are non-zero?
> 
> main<- dummy_raw_data$main %>%
>   select(c("uuid",starts_with("admin"),starts_with("cm"))) %>%
>   add_income_source_cat() %>%
>   select(uuid, cm_income_source_emergency_n, cm_income_source_unstable_n,
>          cm_income_source_stable_n,cm_income_source_other_n, everything())
> 
> I didn’t look into the count_if_above_zero function

**Comment by gnoblet** [comment]
Issue is twofold i think
1. Will double check what's a desired outcome. I guess the question is, should we rank if some components are missing?
2. If you don't run "add_income_source_zero_to_sl.R ](https://github.com/impact-initiatives-hppu/humind/blob/main/R/add_income_source_zero_to_sl.R)" first, which replaces the values that were skipped because they are 0, then obivously, a lot are NAed (also these are dummy data)

**Comment by sunheemoraes** [comment]
As noted in the previous comment by Guillaume, the count_if_above_zero function does not work properly if you don't run "add_income_source_zero_to_sl.R first (i.e. the count of non-zero vars for an income category will be NA is any NAs exist for that category). 

@gnoblet - do we want to nest add_income_source_zero_to_sl.R within add_income_source_cat.R so that we dont take a chance on a country team not applying the first function beforehand? If not maybe even adding a comment. 

Tickets for count_if_above_zero #108/#109 appear to be a separate issue (For example, -2 and 1 are being counted as NA instead of 1 non-zero in the final column) and will be addressed in those tickets.

**Comment by lanawwas** [comment]
Link issue #429

**Comment by gnoblet** [comment]
> As noted in the previous comment by Guillaume, the count_if_above_zero function does not work properly if you don't run "add_income_source_zero_to_sl.R first (i.e. the count of non-zero vars for an income category will be NA is any NAs exist for that category).
> 
> @gnoblet - do we want to nest add_income_source_zero_to_sl.R within add_income_source_cat.R so that we dont take a chance on a country team not applying the first function beforehand? If not maybe even adding a comment.
> 
> Tickets for count_if_above_zero #108/#109 appear to be a separate issue (For example, -2 and 1 are being counted as NA instead of 1 non-zero in the final column) and will be addressed in those tickets.

Great to nest it! At most it would duplicate a calculation, at best we are on the safe side.
