### ISSUE TITLE
add_shelter_issue_cat() function - undefined values 

### ISSUE THREAD

**Issue by Amnah-Harahsheh** [impact-initiatives-hppu/humind#534]
According to the guidline:

"Add a new variable with the count of issues called snfi_shelter_issues_n. If no issues were reported, assign a value of 0. If Don't know, Prefer not to answer or Other was selected, assign a value of -999."

Shelter issues question is select_multiple, and there are cases where 'Other' was selected along with other issues. In these cases, the snfi_shelter_issue_n column is assigned a value of -999, disregarding the other selected issues, and snfi_shelter_issue_cat is assigned a value of "undefined". Could you please double check if this function is correct?

Thanks,

**Comment by sunheemoraes** [comment]
suggested update to be reviewed: 

1. add another parameter for option "Other": -998
2. clean out -999, -998 afterwards in the script in order to remove values from snfi_shelter_issue_n to avoid confusion if country teams uses this helper variable for analysis. 
-----------------------------------------------------------------------
add_shelter_issue_cat <- function(
    df,
    shelter_issue = "snfi_shelter_issue",
    none = "none",
    issues = c("lack_privacy", "lack_space", "temperature", "ventilation", "leak", "lock", "lack_lighting", "difficulty_move"),
    **undefined = c("dnk", "pnta"), #remove "other"
    other = c("other"), #create separate category for "other"**
    sep = "/"){
  
  #------ Checks
  
  # Check if the variable is in the data frame
  if_not_in_stop(df, shelter_issue, "df")
  
  # Prep choices
  shelter_issue_d_issues <- paste0(shelter_issue, sep, issues)
  shelter_issue_d_undefined <- paste0(shelter_issue, sep, undefined)
  **shelter_issue_d_other <- paste0(shelter_issue, sep, other) #add this line**
  shelter_issue_d_none <- paste0(shelter_issue, sep, none)
  
  # Check if columns are in the dataset
  if_not_in_stop(df, c(shelter_issue_d_issues, shelter_issue_d_undefined,  **shelter_issue_d_other**, shelter_issue_d_none), "df") #add shelter_issue_d_other
  
  # Check that colimns are in set 0:1
  are_values_in_set(df, c(shelter_issue_d_issues, shelter_issue_d_undefined,  **shelter_issue_d_other**, shelter_issue_d_none), c(0, 1)) #add shelter_issue_d_other
  
  
  # Check that none is of length 1
  if (length(none) != 1) rlang::abort("none must be of length 1")
  
  #------ Recode
  
  # Sum vars across issues
  df <- sum_vars(
    df,
    new_colname = "snfi_shelter_issue_n",
    vars = shelter_issue_d_issues,
    na_rm = TRUE,
    imputation = "none"
  )
  
  # Add "none," "undefined" and "other" information
  df <- dplyr::mutate(
    df,
    snfi_shelter_issue_n = dplyr::case_when(
      dplyr::if_any(shelter_issue_d_undefined, \(x) x == 1) ~ -999,
      **dplyr::if_any(shelter_issue_d_other, \(x) x == 1) ~ -998,**
      !!rlang::sym(shelter_issue_d_none) == 1 ~ 0,
      .default = !!rlang::sym("snfi_shelter_issue_n")
    )
  )
  
  # Add final recoding
  df <- dplyr::mutate(
    df,
    snfi_shelter_issue_cat = dplyr::case_when(
      snfi_shelter_issue_n == 0 ~ "none",
      snfi_shelter_issue_n == -999 ~ "undefined",
      **snfi_shelter_issue_n == -998 ~ "other",**
      snfi_shelter_issue_n <= 3 ~ "1_to_3",
      snfi_shelter_issue_n <= 6 ~ "4_to_6",
      snfi_shelter_issue_n <= 8 ~ "7_to_8",
      .default = NA_character_
    )
  )
 
**# Change -999 and -998 in snfi_shelter_issue_n to NA
  df <- dplyr::mutate(
    df,
    snfi_shelter_issue_n = dplyr::case_when(
      snfi_shelter_issue_n %in% c(-999, -998) ~ NA_real_,
      .default = snfi_shelter_issue_n
    )
  )**

  return(df)
  
}

**Comment by gnoblet** [comment]
@gnoblet to give feedback, auto tag not to forget

**Comment by sunheemoraes** [comment]
**Summary of changes:** 
1) Create separate category for response option "other" instead of listing as category "undefined." 
2) Change -999 (undefined) and -998 (other) in snfi_shelter_issue_n to NA

Fixes merged into dev2024.1.3.

https://github.com/impact-initiatives-hppu/humind/blob/dev2024.1.3/R/add_shelter_issue_cat.R

**Comment by sunheemoraes** [comment]
Will keep ticket as "opened" until changes are rolled out with new Humind version
