### ISSUE TITLE
Review design of parameters

### ISSUE THREAD

**Issue by gnoblet** [impact-initiatives-hppu/humind#548]
Should parameters be one to one like :
```r
function(yes = "yes, no = "no")
```
or 
```r
function(levels = c("yes", "no"))
```

Based on the outcome of this discussion, update and review package and/or clarify documentation.

**Comment by gnoblet** [comment]
@sunheemoraes Linking issue #547 here if it becomes a broader conversation on the whole package.

**Comment by matteoboh** [comment]
Hello, adding here as most likely linked to this: if you decide to stick to the actual design of parameters as an ordered vector (which I personally do not recommend, as I already saw this leading to mis-categorizations having quite broad consequences on the final results), consider to update the descriptions of the parameters as in some cases they are not coherent with the actual order expected by the function.
- Example 1: `add_comp_wash` has `@param setting_levels Levels for the setting in that order: camp, rural, urban.` [[line 5](https://github.com/impact-initiatives-hppu/humind/blob/d4f9ad85932074a16203a58b6875046c36328ab5/R/add_comp_wash.R#L5)], but the order should be `setting_levels = c("camp", "urban", "rural")` instead [[line 25](https://github.com/impact-initiatives-hppu/humind/blob/d4f9ad85932074a16203a58b6875046c36328ab5/R/add_comp_wash.R#L25C5-L25C49)]
- Example 2: `none` as first option for param `issue_cat_levels` in `add_comp_snfi`, as already flagged in #545 .

Cheers:)

**Comment by sunheemoraes** [comment]
Thank you for the flag @matteoboh. We will update the functions by creating separate parameters instead of only updating the documentations. Below are the functions in Humind that need changes so far. Plan to implement the changes in the next Humind version roll-out. 

- add_loop_healthcare_needed_cat.R
- add_comp_prot.R
- add_comp_snfi.R
- add_comp_wash.R
- add_drinking_water_source_cat.R
